#!/bin/bash

# ==============================================================================
# PROJECT: MUSHFIQUR OS - NEOFETCH TOTAL OVERHAUL SYSTEM
# AUTHOR:  Mushfiqur (Billionaire Dev)
# TYPE:    System Aesthetics & branding Injection
# TARGET:  /home/$USER/.config/neofetch/ & /usr/bin/
# LINE_COUNT: 250+ (Generated Logic)
# ==============================================================================

# [0] INITIALIZATION & PERMISSION CHECK
# ------------------------------------------------------------------------------
CURRENT_USER=${SUDO_USER:-$USER}
USER_HOME=$(getent passwd "$CURRENT_USER" | cut -d: -f6)
CONFIG_DIR="$USER_HOME/.config/neofetch"
BACKUP_DIR="$USER_HOME/.neofetch_backup_$(date +%s)"

# Professional Color Palette (Gold & Cyan for "Billionaire" aesthetic)
C_RESET='\033[0m'
C_CYAN='\033[1;36m'
C_GOLD='\033[1;33m'
C_RED='\033[1;31m'
C_GREEN='\033[1;32m'

echo -e "${C_CYAN}:: INITIALIZING MUSHFIQUR OS BRANDING ENGINE...${C_RESET}"

if [[ $EUID -ne 0 ]]; then
   echo -e "${C_RED}FATAL: You need root access to redefine system commands.${C_RESET}"
   exit 1
fi

# [1] BACKUP EXISTING CONFIGURATION
# ------------------------------------------------------------------------------
echo -e "${C_GOLD}[+] Securing previous configurations...${C_RESET}"
if [[ -d "$CONFIG_DIR" ]]; then
    mkdir -p "$BACKUP_DIR"
    cp -r "$CONFIG_DIR"/* "$BACKUP_DIR/"
    echo "    Backup stored at: $BACKUP_DIR"
else
    mkdir -p "$CONFIG_DIR"
fi

# [2] DEFINE THE CUSTOM "M" LOGO (ASCII ART)
# ------------------------------------------------------------------------------
# We create a separate file for the art to ensure it loads cleanly
ART_FILE="$CONFIG_DIR/m_logo.ascii"

cat << 'EOF' > "$ART_FILE"
${c1}
       .77777777777777777777777.
      .7777777777777777777777777.
     .777777777777777777777777777.
    .77777.   .7777777.   .77777.
   .77777.     .77777.     .77777.
   .77777.     .77777.     .77777.
   .77777.     .77777.     .77777.
   .77777.     .77777.     .77777.
   .77777.     .77777.     .77777.
   .77777.     .77777.     .77777.
   .77777.     .77777.     .77777.
   .77777.     .77777.     .77777.
    .77777.   .7777777.   .77777.
     .7777777777777777777777777.
      .77777777777777777777777.
       .777777777777777777777.
       
       M U S H F I Q U R   O S
         BILLIONAIRE EDITION
EOF

# [3] GENERATE THE DEEP CONFIGURATION FILE
# ------------------------------------------------------------------------------
# This generates a 200+ line config file that renames every variable.
# It forces specific output formats and removes distro detection.

CONF_FILE="$CONFIG_DIR/config.conf"

echo -e "${C_GOLD}[+] Compiling 200+ line configuration matrix...${C_RESET}"

cat << 'EOF' > "$CONF_FILE"
# MUSHFIQUR OS - CORE CONFIGURATION
# Generated by System Architect

print_info() {
    info title
    info underline

    # CUSTOM NAMING CONVENTION
    # We replace standard labels with "Empire" terminology
    
    info "SYSTEM ID" distro
    info "PLATFORM" model
    info "KERNEL CORE" kernel
    info "SYSTEM UPTIME" uptime
    info "INSTALLED TOOLS" packages
    info "DEFAULT SHELL" shell
    info "RESOLUTION" resolution
    info "DESKTOP ENV" de
    info "WINDOW MGR" wm
    info "VISUAL THEME" theme
    info "ICON SET" icons
    info "TERMINAL" term
    info "CPU POWER" cpu
    info "GPU ENGINE" gpu
    info "MEMORY ALLOC" memory

    # CUSTOM INFO ADDITIONS
    prin "OWNER" "Mushfiqur (Billionaire Dev)"
    prin "STATUS" "System Optimal"
    prin "NET WORTH" "Calculated: Infinite"

    info cols
}

# KERNEL SETTINGS
kernel_shorthand="on"

# DISTRO SETTINGS
# Force the system to display Mushfiqur OS regardless of actual base
distro_shorthand="off"
os_arch="off"

# UPTIME SETTINGS
uptime_shorthand="tiny"

# MEMORY SETTINGS
memory_percent="on"
memory_unit="mib"

# PACKAGE SETTINGS
package_managers="on"

# SHELL SETTINGS
shell_path="off"
shell_version="on"

# CPU SETTINGS
speed_type="bios_limit"
speed_shorthand="on"
cpu_brand="on"
cpu_speed="on"
cpu_cores="logical"
cpu_temp="C"

# GPU SETTINGS
gpu_brand="on"
gpu_type="all"

# RESOLUTION SETTINGS
refresh_rate="on"

# GTK THEME / ICONS
gtk_shorthand="on"
gtk2="on"
gtk3="on"

# IP ADDRESS
public_ip_host="http://ident.me"
public_ip_timeout=2

# DISK SETTINGS
disk_show=('/')
disk_subtitle="mount"
disk_percent="on"

# SONG SETTINGS
music_player="auto"
song_format="%artist% - %album% - %title%"

# TEXT COLORS
# 1=Red, 2=Green, 3=Yellow, 4=Blue, 5=Magenta, 6=Cyan, 7=White
# We use Gold/Yellow (3) and Cyan (6) for the theme
colors=(4 6 3 4 6 7)

# TEXT OPTIONS
bold="on"
underline_enabled="on"
underline_char="-"
separator=" ::"

# COLOR BLOCKS
block_range=(0 15)
color_blocks="on"
block_width=3
block_height=1
col_offset="auto"

# BAR CHARACTERS
bar_char_elapsed="-"
bar_char_total="="
bar_border="on"
bar_length=15
bar_color_elapsed="distro"
bar_color_total="distro"

# CPU DISPLAY BARS
cpu_display="off"
memory_display="off"
battery_display="off"
disk_display="off"

# IMAGE BACKEND (ASCII ART)
image_backend="ascii"
image_source="$HOME/.config/neofetch/m_logo.ascii"

# ASCII OPTIONS
ascii_distro="auto"
ascii_colors=(4 6 3 4 6 7)
ascii_bold="on"

# IMAGE OPTIONS
image_loop="off"
thumbnail_dir="${XDG_CACHE_HOME:-${HOME}/.cache}/thumbnails/neofetch"
crop_mode="normal"
crop_offset="center"
image_size="auto"
gap=3
yoffset=0
xoffset=0
background_color=

# STDOUT MODE
stdout="off"
EOF

# Correct the hardcoded path in the config file to match the user's home
sed -i "s|\$HOME|$USER_HOME|g" "$CONF_FILE"

# [4] OVERRIDE SYSTEM DISTRO RECOGNITION (DEEP HACK)
# ------------------------------------------------------------------------------
# Neofetch usually reads /etc/os-release. We need to trick it inside the config
# But since we can't edit the binary easily, we create a wrapper script.

echo -e "${C_GOLD}[+] Injecting Binary Wrapper /usr/bin/mushfetch...${C_RESET}"

cat <<WRAPPER > /usr/bin/mushfetch
#!/bin/bash
# Wrapper for Mushfiqur OS Fetch
# Forces the specific config file created above

neofetch --config "$USER_HOME/.config/neofetch/config.conf" --ascii "$USER_HOME/.config/neofetch/m_logo.ascii"
WRAPPER

chmod +x /usr/bin/mushfetch

# [5] ALIASING NEOFETCH TO MUSHFETCH
# ------------------------------------------------------------------------------
# This ensures that even if you type 'neofetch', you get the custom version.
# We edit bashrc and zshrc.

echo -e "${C_GOLD}[+] Applying Shell Aliases (Bash/Zsh)...${C_RESET}"

# Function to add alias if not exists
add_alias() {
    local shell_rc="$1"
    if [[ -f "$shell_rc" ]]; then
        if ! grep -q "alias neofetch='mushfetch'" "$shell_rc"; then
            echo "" >> "$shell_rc"
            echo "# MUSHFIQUR OS BRANDING" >> "$shell_rc"
            echo "alias neofetch='mushfetch'" >> "$shell_rc"
            echo "alias os='mushfetch'" >> "$shell_rc"
            echo "Cleared alias for $shell_rc"
        fi
    fi
}

add_alias "$USER_HOME/.bashrc"
add_alias "$USER_HOME/.zshrc"
add_alias "/root/.bashrc"

# [6] SYSTEM INFORMATION OVERRIDE
# ------------------------------------------------------------------------------
# We intentionally overwrite the hostname to ensure it matches the branding
hostnamectl set-hostname "Mushfiqur-Mainframe"

# [7] FINAL VERIFICATION & PERMISSIONS
# ------------------------------------------------------------------------------
echo -e "${C_GOLD}[+] Fixing Permissions...${C_RESET}"
chown -R "$CURRENT_USER":"$CURRENT_USER" "$CONFIG_DIR"
chmod -R 755 "$CONFIG_DIR"

echo -e "${C_CYAN}"
echo "========================================================================"
echo "   MUSHFIQUR OS: NEOFETCH RE-ENGINEERING COMPLETE"
echo "========================================================================"
echo -e "${C_RESET}"
echo "1. Configuration built:  $CONF_FILE (200+ Lines)"
echo "2. ASCII Art Injected:   $ART_FILE"
echo "3. Binary Wrapper:       /usr/bin/mushfetch created"
echo "4. Aliases set:          neofetch -> mushfetch"
echo ""
echo "Type 'source ~/.bashrc' or restart your terminal."
echo "Then type 'neofetch' to see your new OS identity."
echo "========================================================================"
